tasks:
  - name: Setup environment and PHP/Composer dependencies
    init: |
      cp .env.example .env &&
      sed -i "s#APP_URL=http://localhost#APP_URL=$(gp url 80)#g" .env
      sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=$(gp url 5173)#g" .env
      composer install --ignore-platform-reqs
      php artisan key:generate
      php artisan storage:link
    command: |
      alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
      sail up -d &&
      sail artisan migrate
      sail artisan db:seed

ports:
  - port: 3306
    onOpen: ignore
    name: MySQL

# Configure vscode
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - ms-azuretools.vscode-docker
    - ecmel.vscode-html-css
    - MehediDracula.php-namespace-resolver
    - Equinusocio.vsc-community-material-theme
    - EditorConfig.EditorConfig
    - streetsidesoftware.code-spell-checker
